version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432" # Оставляю 5435, чтобы не конфликтовало с вашей локальной БД
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # --- ДОБАВЛЕНО: Проверка здоровья БД ---
    healthcheck:
      # Проверяем готовность, пингуя пользователя 'user'
      test: ["CMD-SHELL", "pg_isready -U user"] 
      interval: 5s      # Как часто проверять
      timeout: 5s       # Сколько ждать ответа
      retries: 5        # Сколько раз пытаться перед тем как сдаться
    # ---------------------------------------

  user-service:
    build: ./user-service
    ports:
      - "8081:8080"
    environment:
      DB_URL: "host=postgres user=user password=password dbname=users_db port=5432 sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy # Ждем, пока healthcheck базы скажет "OK"

  order-service:
    build: ./order-service
    ports:
      - "8082:8080"
      - "50052:50051"
    environment:
      DB_URL: "host=postgres user=user password=password dbname=orders_db port=5432 sslmode=disable"
      PAYMENT_SERVICE_URL: "payment-service:50051"
      PORT: 8080
      GRPC_PORT: 50051
    depends_on:
      postgres:
        condition: service_healthy
      # Сервисы могут зависеть друг от друга, но пока достаточно БД
      
  payment-service:
    build: ./payment-service
    ports:
      - "8083:8080"
      - "50053:50051"
    environment:
      DB_URL: "host=postgres user=user password=password dbname=payments_db port=5432 sslmode=disable"
      ORDER_SERVICE_URL: "order-service:50051"
      SHIPPING_SERVICE_URL: "shipping-service:50051"
      PORT: 8080
      GRPC_PORT: 50051
    depends_on:
      postgres:
        condition: service_healthy

  shipping-service:
    build: ./shipping-service
    ports:
      - "8084:8080"
      - "50054:50051"
    environment:
      DB_URL: "host=postgres user=user password=password dbname=shippings_db port=5432 sslmode=disable"
      PORT: 8080
      GRPC_PORT: 50051
    depends_on:
      postgres:
        condition: service_healthy